### ISSUE TITLE
Development setup fails to build

### ISSUE THREAD

**Issue by fedde-s** [cBioPortal/oncoprintjs#51]
When I follow [the instructions](https://github.com/cBioPortal/oncoprintjs/blob/v1.0.76/README.md#getting-started) on how to build the playground, gulp fails with the following error message:

```
[12:47:48] Using gulpfile ~/git/oncoprintjs/gulpfile.js
[12:47:48] Starting 'default'...
Error: Cannot find module 'worker-loader?inline=true&fallback=false!./workers/clustering-worker.js' from '/Users/fedde/git/oncoprintjs/src/js'
    at /Users/fedde/git/oncoprintjs/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/fedde/git/oncoprintjs/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/fedde/git/oncoprintjs/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/fedde/git/oncoprintjs/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/fedde/git/oncoprintjs/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/fedde/git/oncoprintjs/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
[12:47:49] 'default' errored after 963 ms
[12:47:49] Error in plugin "gulp-shell"
Message:
    Command `browserify src/js/main.js -o dist/oncoprint-bundle.js` failed with exit code 1
```

**Comment by fedde-s** [comment]
The bug was introduced by commit 9288757da5faa617b97aeb3258d2477728c4f6f7.

**Comment by adamabeshouse** [comment]
Sorry that is out of date, we use webpack now.

**Comment by adamabeshouse** [comment]
Documentation has been updated.
